#!/bin/sh
set -e 

PWD=$(pwd)
docker run ${PLATFORM_OPTIONS}	\
	-e HOME=${PWD}				\
	-v ${PWD}:${PWD} 			\
	-w ${PWD} 					\
	-v /var/run/docker.sock:/var/run/docker.sock \
	--interactive 										\
	--rm 										 		\
	"$@"
